name: Go

on:
  push:
    branches: [master]
    paths:
      - "cli/**"
  pull_request:
    branches: [master]
    paths:
      - "cli/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v -o /dev/null
        working-directory: "./cli"

      - name: Install staticcheck
        run: go get honnef.co/go/tools/cmd/staticcheck

      - name: Run staticcheck
        run: staticcheck ./...
        working-directory: "./cli"

      - name: Test
        run: go test -v ./...
